"""Edited type column in ServiceCustomerAttachment model

Revision ID: 826ae1cbdbbc
Revises: d54ab9ca8dd0
Create Date: 2026-10-09 10:51:20.919331

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '826ae1cbdbbc'
down_revision = 'd54ab9ca8dd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_customer_attachments', schema=None) as batch_op:
        batch_op.drop_column('type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_customer_attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
